apiVersion: v1
kind: PersistentVolume
metadata:
  name: de-face-volume
  labels:
    app: de-inference
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/general
    server: 128.84.48.178
    readOnly: false
